[package]
name = "flank"
version = "0.5.0"
authors = ["Ryan Taylor <ryan@ryantaylordev.ca>"]

[dependencies]
clap = "1"
log4rs = "0.3"
rustc-serialize = "0.3"
vault = "1"

[dependencies.clippy]
version = "*"
optional = true

[features]
dev = ["clippy"]